apiVersion: skiperator.kartverket.no/v1beta1
kind: SKIPJob
metadata:
  name: databricks-til-elastic
  namespace: matrikkel-main
spec:
  cron:
    # Hver natt kl 03:00 UTC. SKIP-jobber kjører i UTC med mindre timeZone
    # er satt - se dokumentasjonen.
    schedule: "0 3 * * *"
  job:
    ttlSecondsAfterFinished: 3600
    activeDeadlineSeconds: 3600
  image: "{{image}}"
  resources:
    limits:
      memory: 1G
    requests:
      cpu: 100m
      memory: 512M
  accessPolicy:
    outbound:
      external:
        - host: matrikkelen-adrs-dev-cf782b.es.europe-north1.gcp.elastic-cloud.com
  env:
    - name: DATABRICKS_TABLE
      value: "catalog.skjema.matrikkel_adresse" # TODO: riktig catalog.skjema
    - name: ES_URL
      value: "https://matrikkelen-adrs-dev-cf782b.es.europe-north1.gcp.elastic-cloud.com"
    - name: ES_API_KEY
      gsmSecretName: "databricks-to-elastic-es-api-key"
    - name: TZ
      value: "UTC"
